package com.my.raido.services

enum class BookingStatus {
   NO_RIDE, PENDING, ACCEPTED, REJECTED, SELECT_VEHICLE,LOOKING_DRIVER, RIDE_CANCELLED, RIDE_ACCEPTED, ARRIVEING, ARRIVED, RIDE_STARTED, RIDE_COMPLETED,  CONFIRM, CANCEL
}